# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.25

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/mr-geri/Проекты/c/two_course/coursework

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/mr-geri/Проекты/c/two_course/coursework

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/mr-geri/Проекты/c/two_course/coursework/CMakeFiles /home/mr-geri/Проекты/c/two_course/coursework//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/mr-geri/Проекты/c/two_course/coursework/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -P /home/mr-geri/Проекты/c/two_course/coursework/CMakeFiles/VerifyGlobs.cmake
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named coursework

# Build rule for target.
coursework: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 coursework
.PHONY : coursework

# fast build rule for target.
coursework/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/coursework.dir/build.make CMakeFiles/coursework.dir/build
.PHONY : coursework/fast

#=============================================================================
# Target rules for targets named coursework_autogen

# Build rule for target.
coursework_autogen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 coursework_autogen
.PHONY : coursework_autogen

# fast build rule for target.
coursework_autogen/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/coursework_autogen.dir/build.make CMakeFiles/coursework_autogen.dir/build
.PHONY : coursework_autogen/fast

coursework_autogen/EWIEGA46WW/qrc_resource.o: coursework_autogen/EWIEGA46WW/qrc_resource.cpp.o
.PHONY : coursework_autogen/EWIEGA46WW/qrc_resource.o

# target to build an object file
coursework_autogen/EWIEGA46WW/qrc_resource.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/coursework.dir/build.make CMakeFiles/coursework.dir/coursework_autogen/EWIEGA46WW/qrc_resource.cpp.o
.PHONY : coursework_autogen/EWIEGA46WW/qrc_resource.cpp.o

coursework_autogen/EWIEGA46WW/qrc_resource.i: coursework_autogen/EWIEGA46WW/qrc_resource.cpp.i
.PHONY : coursework_autogen/EWIEGA46WW/qrc_resource.i

# target to preprocess a source file
coursework_autogen/EWIEGA46WW/qrc_resource.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/coursework.dir/build.make CMakeFiles/coursework.dir/coursework_autogen/EWIEGA46WW/qrc_resource.cpp.i
.PHONY : coursework_autogen/EWIEGA46WW/qrc_resource.cpp.i

coursework_autogen/EWIEGA46WW/qrc_resource.s: coursework_autogen/EWIEGA46WW/qrc_resource.cpp.s
.PHONY : coursework_autogen/EWIEGA46WW/qrc_resource.s

# target to generate assembly for a file
coursework_autogen/EWIEGA46WW/qrc_resource.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/coursework.dir/build.make CMakeFiles/coursework.dir/coursework_autogen/EWIEGA46WW/qrc_resource.cpp.s
.PHONY : coursework_autogen/EWIEGA46WW/qrc_resource.cpp.s

coursework_autogen/mocs_compilation.o: coursework_autogen/mocs_compilation.cpp.o
.PHONY : coursework_autogen/mocs_compilation.o

# target to build an object file
coursework_autogen/mocs_compilation.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/coursework.dir/build.make CMakeFiles/coursework.dir/coursework_autogen/mocs_compilation.cpp.o
.PHONY : coursework_autogen/mocs_compilation.cpp.o

coursework_autogen/mocs_compilation.i: coursework_autogen/mocs_compilation.cpp.i
.PHONY : coursework_autogen/mocs_compilation.i

# target to preprocess a source file
coursework_autogen/mocs_compilation.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/coursework.dir/build.make CMakeFiles/coursework.dir/coursework_autogen/mocs_compilation.cpp.i
.PHONY : coursework_autogen/mocs_compilation.cpp.i

coursework_autogen/mocs_compilation.s: coursework_autogen/mocs_compilation.cpp.s
.PHONY : coursework_autogen/mocs_compilation.s

# target to generate assembly for a file
coursework_autogen/mocs_compilation.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/coursework.dir/build.make CMakeFiles/coursework.dir/coursework_autogen/mocs_compilation.cpp.s
.PHONY : coursework_autogen/mocs_compilation.cpp.s

figures/arrow/arrow.o: figures/arrow/arrow.cpp.o
.PHONY : figures/arrow/arrow.o

# target to build an object file
figures/arrow/arrow.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/coursework.dir/build.make CMakeFiles/coursework.dir/figures/arrow/arrow.cpp.o
.PHONY : figures/arrow/arrow.cpp.o

figures/arrow/arrow.i: figures/arrow/arrow.cpp.i
.PHONY : figures/arrow/arrow.i

# target to preprocess a source file
figures/arrow/arrow.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/coursework.dir/build.make CMakeFiles/coursework.dir/figures/arrow/arrow.cpp.i
.PHONY : figures/arrow/arrow.cpp.i

figures/arrow/arrow.s: figures/arrow/arrow.cpp.s
.PHONY : figures/arrow/arrow.s

# target to generate assembly for a file
figures/arrow/arrow.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/coursework.dir/build.make CMakeFiles/coursework.dir/figures/arrow/arrow.cpp.s
.PHONY : figures/arrow/arrow.cpp.s

figures/figure/figure.o: figures/figure/figure.cpp.o
.PHONY : figures/figure/figure.o

# target to build an object file
figures/figure/figure.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/coursework.dir/build.make CMakeFiles/coursework.dir/figures/figure/figure.cpp.o
.PHONY : figures/figure/figure.cpp.o

figures/figure/figure.i: figures/figure/figure.cpp.i
.PHONY : figures/figure/figure.i

# target to preprocess a source file
figures/figure/figure.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/coursework.dir/build.make CMakeFiles/coursework.dir/figures/figure/figure.cpp.i
.PHONY : figures/figure/figure.cpp.i

figures/figure/figure.s: figures/figure/figure.cpp.s
.PHONY : figures/figure/figure.s

# target to generate assembly for a file
figures/figure/figure.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/coursework.dir/build.make CMakeFiles/coursework.dir/figures/figure/figure.cpp.s
.PHONY : figures/figure/figure.cpp.s

figures/hexagon/hexagon.o: figures/hexagon/hexagon.cpp.o
.PHONY : figures/hexagon/hexagon.o

# target to build an object file
figures/hexagon/hexagon.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/coursework.dir/build.make CMakeFiles/coursework.dir/figures/hexagon/hexagon.cpp.o
.PHONY : figures/hexagon/hexagon.cpp.o

figures/hexagon/hexagon.i: figures/hexagon/hexagon.cpp.i
.PHONY : figures/hexagon/hexagon.i

# target to preprocess a source file
figures/hexagon/hexagon.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/coursework.dir/build.make CMakeFiles/coursework.dir/figures/hexagon/hexagon.cpp.i
.PHONY : figures/hexagon/hexagon.cpp.i

figures/hexagon/hexagon.s: figures/hexagon/hexagon.cpp.s
.PHONY : figures/hexagon/hexagon.s

# target to generate assembly for a file
figures/hexagon/hexagon.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/coursework.dir/build.make CMakeFiles/coursework.dir/figures/hexagon/hexagon.cpp.s
.PHONY : figures/hexagon/hexagon.cpp.s

figures/line/line.o: figures/line/line.cpp.o
.PHONY : figures/line/line.o

# target to build an object file
figures/line/line.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/coursework.dir/build.make CMakeFiles/coursework.dir/figures/line/line.cpp.o
.PHONY : figures/line/line.cpp.o

figures/line/line.i: figures/line/line.cpp.i
.PHONY : figures/line/line.i

# target to preprocess a source file
figures/line/line.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/coursework.dir/build.make CMakeFiles/coursework.dir/figures/line/line.cpp.i
.PHONY : figures/line/line.cpp.i

figures/line/line.s: figures/line/line.cpp.s
.PHONY : figures/line/line.s

# target to generate assembly for a file
figures/line/line.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/coursework.dir/build.make CMakeFiles/coursework.dir/figures/line/line.cpp.s
.PHONY : figures/line/line.cpp.s

figures/parallelepiped/parallelepiped.o: figures/parallelepiped/parallelepiped.cpp.o
.PHONY : figures/parallelepiped/parallelepiped.o

# target to build an object file
figures/parallelepiped/parallelepiped.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/coursework.dir/build.make CMakeFiles/coursework.dir/figures/parallelepiped/parallelepiped.cpp.o
.PHONY : figures/parallelepiped/parallelepiped.cpp.o

figures/parallelepiped/parallelepiped.i: figures/parallelepiped/parallelepiped.cpp.i
.PHONY : figures/parallelepiped/parallelepiped.i

# target to preprocess a source file
figures/parallelepiped/parallelepiped.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/coursework.dir/build.make CMakeFiles/coursework.dir/figures/parallelepiped/parallelepiped.cpp.i
.PHONY : figures/parallelepiped/parallelepiped.cpp.i

figures/parallelepiped/parallelepiped.s: figures/parallelepiped/parallelepiped.cpp.s
.PHONY : figures/parallelepiped/parallelepiped.s

# target to generate assembly for a file
figures/parallelepiped/parallelepiped.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/coursework.dir/build.make CMakeFiles/coursework.dir/figures/parallelepiped/parallelepiped.cpp.s
.PHONY : figures/parallelepiped/parallelepiped.cpp.s

figures/rectangle/rectangle.o: figures/rectangle/rectangle.cpp.o
.PHONY : figures/rectangle/rectangle.o

# target to build an object file
figures/rectangle/rectangle.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/coursework.dir/build.make CMakeFiles/coursework.dir/figures/rectangle/rectangle.cpp.o
.PHONY : figures/rectangle/rectangle.cpp.o

figures/rectangle/rectangle.i: figures/rectangle/rectangle.cpp.i
.PHONY : figures/rectangle/rectangle.i

# target to preprocess a source file
figures/rectangle/rectangle.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/coursework.dir/build.make CMakeFiles/coursework.dir/figures/rectangle/rectangle.cpp.i
.PHONY : figures/rectangle/rectangle.cpp.i

figures/rectangle/rectangle.s: figures/rectangle/rectangle.cpp.s
.PHONY : figures/rectangle/rectangle.s

# target to generate assembly for a file
figures/rectangle/rectangle.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/coursework.dir/build.make CMakeFiles/coursework.dir/figures/rectangle/rectangle.cpp.s
.PHONY : figures/rectangle/rectangle.cpp.s

figures/rectangleOval/rectangleOval.o: figures/rectangleOval/rectangleOval.cpp.o
.PHONY : figures/rectangleOval/rectangleOval.o

# target to build an object file
figures/rectangleOval/rectangleOval.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/coursework.dir/build.make CMakeFiles/coursework.dir/figures/rectangleOval/rectangleOval.cpp.o
.PHONY : figures/rectangleOval/rectangleOval.cpp.o

figures/rectangleOval/rectangleOval.i: figures/rectangleOval/rectangleOval.cpp.i
.PHONY : figures/rectangleOval/rectangleOval.i

# target to preprocess a source file
figures/rectangleOval/rectangleOval.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/coursework.dir/build.make CMakeFiles/coursework.dir/figures/rectangleOval/rectangleOval.cpp.i
.PHONY : figures/rectangleOval/rectangleOval.cpp.i

figures/rectangleOval/rectangleOval.s: figures/rectangleOval/rectangleOval.cpp.s
.PHONY : figures/rectangleOval/rectangleOval.s

# target to generate assembly for a file
figures/rectangleOval/rectangleOval.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/coursework.dir/build.make CMakeFiles/coursework.dir/figures/rectangleOval/rectangleOval.cpp.s
.PHONY : figures/rectangleOval/rectangleOval.cpp.s

figures/rhomb/rhomb.o: figures/rhomb/rhomb.cpp.o
.PHONY : figures/rhomb/rhomb.o

# target to build an object file
figures/rhomb/rhomb.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/coursework.dir/build.make CMakeFiles/coursework.dir/figures/rhomb/rhomb.cpp.o
.PHONY : figures/rhomb/rhomb.cpp.o

figures/rhomb/rhomb.i: figures/rhomb/rhomb.cpp.i
.PHONY : figures/rhomb/rhomb.i

# target to preprocess a source file
figures/rhomb/rhomb.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/coursework.dir/build.make CMakeFiles/coursework.dir/figures/rhomb/rhomb.cpp.i
.PHONY : figures/rhomb/rhomb.cpp.i

figures/rhomb/rhomb.s: figures/rhomb/rhomb.cpp.s
.PHONY : figures/rhomb/rhomb.s

# target to generate assembly for a file
figures/rhomb/rhomb.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/coursework.dir/build.make CMakeFiles/coursework.dir/figures/rhomb/rhomb.cpp.s
.PHONY : figures/rhomb/rhomb.cpp.s

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/coursework.dir/build.make CMakeFiles/coursework.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/coursework.dir/build.make CMakeFiles/coursework.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/coursework.dir/build.make CMakeFiles/coursework.dir/main.cpp.s
.PHONY : main.cpp.s

main_window/main_window.o: main_window/main_window.cpp.o
.PHONY : main_window/main_window.o

# target to build an object file
main_window/main_window.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/coursework.dir/build.make CMakeFiles/coursework.dir/main_window/main_window.cpp.o
.PHONY : main_window/main_window.cpp.o

main_window/main_window.i: main_window/main_window.cpp.i
.PHONY : main_window/main_window.i

# target to preprocess a source file
main_window/main_window.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/coursework.dir/build.make CMakeFiles/coursework.dir/main_window/main_window.cpp.i
.PHONY : main_window/main_window.cpp.i

main_window/main_window.s: main_window/main_window.cpp.s
.PHONY : main_window/main_window.s

# target to generate assembly for a file
main_window/main_window.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/coursework.dir/build.make CMakeFiles/coursework.dir/main_window/main_window.cpp.s
.PHONY : main_window/main_window.cpp.s

myGraphicsScene/myGraphicsScene.o: myGraphicsScene/myGraphicsScene.cpp.o
.PHONY : myGraphicsScene/myGraphicsScene.o

# target to build an object file
myGraphicsScene/myGraphicsScene.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/coursework.dir/build.make CMakeFiles/coursework.dir/myGraphicsScene/myGraphicsScene.cpp.o
.PHONY : myGraphicsScene/myGraphicsScene.cpp.o

myGraphicsScene/myGraphicsScene.i: myGraphicsScene/myGraphicsScene.cpp.i
.PHONY : myGraphicsScene/myGraphicsScene.i

# target to preprocess a source file
myGraphicsScene/myGraphicsScene.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/coursework.dir/build.make CMakeFiles/coursework.dir/myGraphicsScene/myGraphicsScene.cpp.i
.PHONY : myGraphicsScene/myGraphicsScene.cpp.i

myGraphicsScene/myGraphicsScene.s: myGraphicsScene/myGraphicsScene.cpp.s
.PHONY : myGraphicsScene/myGraphicsScene.s

# target to generate assembly for a file
myGraphicsScene/myGraphicsScene.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/coursework.dir/build.make CMakeFiles/coursework.dir/myGraphicsScene/myGraphicsScene.cpp.s
.PHONY : myGraphicsScene/myGraphicsScene.cpp.s

myGraphicsView/myGraphicsView.o: myGraphicsView/myGraphicsView.cpp.o
.PHONY : myGraphicsView/myGraphicsView.o

# target to build an object file
myGraphicsView/myGraphicsView.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/coursework.dir/build.make CMakeFiles/coursework.dir/myGraphicsView/myGraphicsView.cpp.o
.PHONY : myGraphicsView/myGraphicsView.cpp.o

myGraphicsView/myGraphicsView.i: myGraphicsView/myGraphicsView.cpp.i
.PHONY : myGraphicsView/myGraphicsView.i

# target to preprocess a source file
myGraphicsView/myGraphicsView.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/coursework.dir/build.make CMakeFiles/coursework.dir/myGraphicsView/myGraphicsView.cpp.i
.PHONY : myGraphicsView/myGraphicsView.cpp.i

myGraphicsView/myGraphicsView.s: myGraphicsView/myGraphicsView.cpp.s
.PHONY : myGraphicsView/myGraphicsView.s

# target to generate assembly for a file
myGraphicsView/myGraphicsView.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/coursework.dir/build.make CMakeFiles/coursework.dir/myGraphicsView/myGraphicsView.cpp.s
.PHONY : myGraphicsView/myGraphicsView.cpp.s

randomPoints/randomPoints.o: randomPoints/randomPoints.cpp.o
.PHONY : randomPoints/randomPoints.o

# target to build an object file
randomPoints/randomPoints.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/coursework.dir/build.make CMakeFiles/coursework.dir/randomPoints/randomPoints.cpp.o
.PHONY : randomPoints/randomPoints.cpp.o

randomPoints/randomPoints.i: randomPoints/randomPoints.cpp.i
.PHONY : randomPoints/randomPoints.i

# target to preprocess a source file
randomPoints/randomPoints.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/coursework.dir/build.make CMakeFiles/coursework.dir/randomPoints/randomPoints.cpp.i
.PHONY : randomPoints/randomPoints.cpp.i

randomPoints/randomPoints.s: randomPoints/randomPoints.cpp.s
.PHONY : randomPoints/randomPoints.s

# target to generate assembly for a file
randomPoints/randomPoints.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/coursework.dir/build.make CMakeFiles/coursework.dir/randomPoints/randomPoints.cpp.s
.PHONY : randomPoints/randomPoints.cpp.s

text/text.o: text/text.cpp.o
.PHONY : text/text.o

# target to build an object file
text/text.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/coursework.dir/build.make CMakeFiles/coursework.dir/text/text.cpp.o
.PHONY : text/text.cpp.o

text/text.i: text/text.cpp.i
.PHONY : text/text.i

# target to preprocess a source file
text/text.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/coursework.dir/build.make CMakeFiles/coursework.dir/text/text.cpp.i
.PHONY : text/text.cpp.i

text/text.s: text/text.cpp.s
.PHONY : text/text.s

# target to generate assembly for a file
text/text.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/coursework.dir/build.make CMakeFiles/coursework.dir/text/text.cpp.s
.PHONY : text/text.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... coursework_autogen"
	@echo "... coursework"
	@echo "... coursework_autogen/EWIEGA46WW/qrc_resource.o"
	@echo "... coursework_autogen/EWIEGA46WW/qrc_resource.i"
	@echo "... coursework_autogen/EWIEGA46WW/qrc_resource.s"
	@echo "... coursework_autogen/mocs_compilation.o"
	@echo "... coursework_autogen/mocs_compilation.i"
	@echo "... coursework_autogen/mocs_compilation.s"
	@echo "... figures/arrow/arrow.o"
	@echo "... figures/arrow/arrow.i"
	@echo "... figures/arrow/arrow.s"
	@echo "... figures/figure/figure.o"
	@echo "... figures/figure/figure.i"
	@echo "... figures/figure/figure.s"
	@echo "... figures/hexagon/hexagon.o"
	@echo "... figures/hexagon/hexagon.i"
	@echo "... figures/hexagon/hexagon.s"
	@echo "... figures/line/line.o"
	@echo "... figures/line/line.i"
	@echo "... figures/line/line.s"
	@echo "... figures/parallelepiped/parallelepiped.o"
	@echo "... figures/parallelepiped/parallelepiped.i"
	@echo "... figures/parallelepiped/parallelepiped.s"
	@echo "... figures/rectangle/rectangle.o"
	@echo "... figures/rectangle/rectangle.i"
	@echo "... figures/rectangle/rectangle.s"
	@echo "... figures/rectangleOval/rectangleOval.o"
	@echo "... figures/rectangleOval/rectangleOval.i"
	@echo "... figures/rectangleOval/rectangleOval.s"
	@echo "... figures/rhomb/rhomb.o"
	@echo "... figures/rhomb/rhomb.i"
	@echo "... figures/rhomb/rhomb.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... main_window/main_window.o"
	@echo "... main_window/main_window.i"
	@echo "... main_window/main_window.s"
	@echo "... myGraphicsScene/myGraphicsScene.o"
	@echo "... myGraphicsScene/myGraphicsScene.i"
	@echo "... myGraphicsScene/myGraphicsScene.s"
	@echo "... myGraphicsView/myGraphicsView.o"
	@echo "... myGraphicsView/myGraphicsView.i"
	@echo "... myGraphicsView/myGraphicsView.s"
	@echo "... randomPoints/randomPoints.o"
	@echo "... randomPoints/randomPoints.i"
	@echo "... randomPoints/randomPoints.s"
	@echo "... text/text.o"
	@echo "... text/text.i"
	@echo "... text/text.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -P /home/mr-geri/Проекты/c/two_course/coursework/CMakeFiles/VerifyGlobs.cmake
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

