// This file is autogenerated. Changes will be overwritten.
#include "PDH6BJJCOA/moc_figure.cpp"
#include "TQNZCBDM3P/moc_rectangle.cpp"
#include "7YTNYDDD2B/moc_rhomb.cpp"
#include "TXKPOHTVN7/moc_main_window.cpp"
#include "OIYP2VNH46/moc_myGraphicScene.cpp"
#include "VCNREXAN4N/moc_myGraphicView.cpp"
